apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
  namespace: devops
type: Opaque
data:
  DRONE_GITHUB_CLIENT_ID: "MWQ4OWE0ODUxOTY1Yjg0NTg1MzQ=" # echo "1d89a4851965b8458534" | base64
  DRONE_GITHUB_CLIENT_SECRET: "YTE4ZmUwMTBkMDNlNGJhZTk0MDNkNzBmNTk4MjZiMDk4MTM5YzE0Yw==" # echo "a18fe010d03e4bae9403d70f59826b098139c14c" | base64
  DRONE_RPC_SECRET: "NTFlNmRkZmEzOTVmNzk1YmEyMTU0Nzc3ZDQ4OGNjMzg=" # echo $(openssl rand -hex 16) | base64
  DRONE_DATABASE_DATASOURCE: "cG9zdGdyZXM6Ly9wb3N0Z3Jlc2FkbWluOmFkbWluMTIzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXNkYj9zc2xtb2RlPWRpc2FibGU=" # "postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable"
  DRONE_USER_CREATE: "dXNlcm5hbWU6bWFyY29zLWhlcjE5OTMtaW1pdCxhZG1pbjp0cnVl" #  username:marcos-her1993-imit,admin:true
  DRONE_SERVER_HOST: "ZHJvbmUubWV0YWxjbG91ZC5jbA==" #  drone.metalcloud.cl
