kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: argocd
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - argo.metalcloud.cl
      secretName: argo-secret-tls
  rules:
    - host: argo.metalcloud.cl
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: 443
