apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
  labels:
    app: konga
spec:
  selector:
    matchLabels:
      app: konga
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: web
        image: pantsel/konga
        resources: {}
        env:
        - name: KONGA_ENV
          value: Production
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_ENV
          value: Production
        - name: DB_ADAPTER
          value: postgres
        - name: DB_HOST
          value: kong-postgresql.kong.svc
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: kong
        - name: DB_USER
          value: kong
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgresql-password
        ports:
        - containerPort: 1338
          name: web
